advcbv/urls.py
from django.contrib import admin
from django.urls import path , re_path ,include
from basic_app import views


urlpatterns = [
   # re_path(r'^$', views.index, name='index'),  #function based
    re_path(r'^$', views.IndexView.as_view()),      # class based
    path('admin/', admin.site.urls),
    re_path(r'^basic_app/',include('basic_app.urls', namespace='basic_app')),
]

basic_app/urls.py
from django.urls import path , re_path
from . import views

app_name = 'basic_app'

urlpatterns = [

    re_path(r'^$', views.SchoolListView.as_view(),name='list'),
    re_path(r'^(?P<pk>\d+)/$',views.SchooDetailView.as_view(),name='detail'),
    re_path(r'^create/$', views.SchoolCreateView.as_view(), name='create'),
    re_path(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    re_path(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),

    
]

basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class School(models.Model):

    name=models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:detail',kwargs={'pk':self.pk})

class Student(models.Model):

    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,on_delete=models.CASCADE, related_name='students') 
    
    def __str__(self):
        return self.name

basic_app/views.py
from django.shortcuts import render ,HttpResponse
from django.urls import reverse_lazy

from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView

from . import models



class IndexView(TemplateView):

     template_name = 'index.html'

    #  def get_context_data(self, **kwargs):
    #      context = super().get_context_data(**kwargs)
    #      context['injectme']= 'Basic Inject!'
    #      return context




class SchoolListView(ListView):
    
    context_object_name ='schools'
    model = models.School   # default returns school_list

class SchooDetailView(DetailView):

    context_object_name ='school_detail'
    model = models.School   # default returns school
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    
    fields =('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    
    fields =('name','principal')
    model = models.School


class SchoolDeleteView(DeleteView):

    model = models.School
    success_url = reverse_lazy('basic_app:list')











# Create your views here.

# class CBView(View):

#     def get(self,request):

#         return HttpResponse('Class based ares cool')

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">

        <ul class="nav navbar-nav">

            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href=""></a></li>
        </ul>
    </nav>

    <div class="container">

        {% block body_block %}

        {% endblock %}

    </div>

   
    
</body>
</html>

basic_app/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}



{% block body_block %}

<h1>Welcome to Other Page</h1>


{% endblock %}

basic_app/templates/basic_app/school_confirm_delete.html
<!DOCTYPE html>
{% extends 'basic_app/basic_app_base.html' %}


{% block body_block %}

<h1>Delete {{school.name}}?</h1>
<form method="post">
    {% csrf_token %}

    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:list' %}">Cancel</a>
    
</form>

{% endblock %}

basic_app/templates/basic_app/school_detail.html
<!DOCTYPE html>
{% extends 'basic_app/basic_app_base.html' %}


{% block body_block %}

  <div class="jumbotron">

    <h1>Welcome to the School Details Page</h1>
    <h1>School Details:</h1>
    <p>Name:      {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location:  {{school_detail.location}}</p>

    <h3>Students:</h3>

    {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old. </p>

    {%endfor%}
  </div>

  <div class="container">

    <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>

    <a class="btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a></p>
   
    

  </div>

{% endblock %}

basic_app/templates/basic_app/school_form.html
<!DOCTYPE html>
{% extends 'basic_app/basic_app_base.html' %}


{% block body_block %}

   <h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
   </h1>
   <form method="post">

     {% csrf_token %}
     {{form.as_p}}
     <input type="submit" class="btn btn-primary" value="Submit">
   </form>

{% endblock %}

basic_app/templates/basic_app/school_list.html
<!DOCTYPE html>
{% extends 'basic_app/basic_app_base.html' %}


{% block body_block %}

    <h1>Welcome To The List Of All Schools</h1>

    <ol>

        {% for school in schools %}

            <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>

        {% endfor  %}

        
    </ol>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">

        <ul class="nav navbar-nav">

            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href=""></a></li>
        </ul>
    </nav>

    <div class="container">

        {% block body_block %}

        {% endblock %}

    </div>

   
    
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}



{% block body_block %}

<div class="jumbotron">
 
    <h1>Home Page</h1>

</div>


{% endblock %}